### ISSUE TITLE
IPv issues with Java 8

### ISSUE THREAD

**Issue by Nilhcem** [Nilhcem/FakeSMTP#34]
"If I want to use FakeSMTP with Java 8, I have to specify that it should use the IPv4 stack instead of the IPv6 stack. Otherwise, FakeSMTP doesn’t work properly."

**Comment by Vest** [comment]
Hello @Nilhcem,

I would like to look at the issue. Could you please tell me how to reproduce it? I have Java 8 (I am using OS X currently with Java 8 (51)).

Kind regards,
Vest

**Comment by Vest** [comment]
Hm. It seems that I haven't tested all features properly. If you start the data binding on localhost:2525, the server starts well. However after the integration tests run, the exception below is thrown:
```txt
java -jar fakeSMTP-2.1-SNAPSHOT.jar -a 127.0.0.1 -b -s -p 2525

28 Jul 2015 21:13:25 INFO  org.subethamail.smtp.server.SMTPServer - SMTP server /127.0.0.1:2525 starting
28 Jul 2015 21:13:25 INFO  org.subethamail.smtp.server.ServerThread - SMTP server /127.0.0.1:2525 started
Exception in thread "org.subethamail.smtp.server.ServerThread /127.0.0.1:2525" java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
	at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:121)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:440)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:396)
	at ch.qos.logback.classic.Logger.error(Logger.java:559)
	at org.subethamail.smtp.server.ServerThread.run(ServerThread.java:81)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.spi.ThrowableProxy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
```

**Comment by SergeyDjam** [comment]
Hello! 

I'm started FakeSMTP 
java -jar fakeSMTP-2.0.jar --start-server --port 2525 --bind-address 127.0.0.1
27 окт 2016 02:43:45 INFO  org.subethamail.smtp.server.SMTPServer - SMTP server *:2525 starting
27 окт 2016 02:43:45 INFO  org.subethamail.smtp.server.ServerThread - SMTP server *:2525 started

and view:
netstat -apn | grep 2525
tcp6       0      0 :::2525                 :::*                    LISTEN      18744/java    

java -jar fakeSMTP-2.0.jar -b --start-server --port 2525 --bind-address 127.0.0.1
27 окт 2016 02:44:51 INFO  org.subethamail.smtp.server.SMTPServer - SMTP server /127.0.0.1:2525 starting
27 окт 2016 02:44:51 INFO  org.subethamail.smtp.server.ServerThread - SMTP server /127.0.0.1:2525 started

and view:
netstat -apn | grep 2525
tcp6       0      0 127.0.0.1:2525          :::*                    LISTEN      18866/java 

tcp6 only? why? This may be fixed?
