### ISSUE TITLE
No EML Reader

### ISSUE THREAD

**Issue by aronrodrigues** [Nilhcem/FakeSMTP#6]
In my system (without a mailClient), when I try to open the eml file, I receive an error.

```
       12 Dez 2013 22:11:00 ERROR com.nilhcem.fakesmtp.gui.tab.MailsListPane - java.io.IOException: Failed to open E:\Users\Aron Rodrigues\Desktop\received-emails\121213100900205.eml. Error message: A device attached to the system is not functioning.
        at sun.awt.windows.WDesktopPeer.ShellExecute(WDesktopPeer.java:76) ~[na:1.7.0_40]
        at sun.awt.windows.WDesktopPeer.open(WDesktopPeer.java:54) ~[na:1.7.0_40]
        at java.awt.Desktop.open(Desktop.java:272) ~[na:1.7.0_40]
        at com.nilhcem.fakesmtp.gui.tab.MailsListPane$3.mouseClicked(MailsListPane.java:118) ~[fakeSMTP-1.5.jar:na]
        at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270) [na:1.7.0_40]
        at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269) [na:1.7.0_40]
        at java.awt.Component.processMouseEvent(Component.java:6508) [na:1.7.0_40]
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3320) [na:1.7.0_40]
        at java.awt.Component.processEvent(Component.java:6270) [na:1.7.0_40]
        at java.awt.Container.processEvent(Container.java:2229) [na:1.7.0_40]
        at java.awt.Component.dispatchEventImpl(Component.java:4861) [na:1.7.0_40]
        at java.awt.Container.dispatchEventImpl(Container.java:2287) [na:1.7.0_40]
        at java.awt.Component.dispatchEvent(Component.java:4687) [na:1.7.0_40]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832) [na:1.7.0_40]
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4501) [na:1.7.0_40]
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422) [na:1.7.0_40]
        at java.awt.Container.dispatchEventImpl(Container.java:2273) [na:1.7.0_40]
        at java.awt.Window.dispatchEventImpl(Window.java:2719) [na:1.7.0_40]
        at java.awt.Component.dispatchEvent(Component.java:4687) [na:1.7.0_40]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735) [na:1.7.0_40]
        at java.awt.EventQueue.access$200(EventQueue.java:103) [na:1.7.0_40]
        at java.awt.EventQueue$3.run(EventQueue.java:694) [na:1.7.0_40]
        at java.awt.EventQueue$3.run(EventQueue.java:692) [na:1.7.0_40]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_40]
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76) [na:1.7.0_40]
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87) [na:1.7.0_40]
        at java.awt.EventQueue$4.run(EventQueue.java:708) [na:1.7.0_40]
        at java.awt.EventQueue$4.run(EventQueue.java:706) [na:1.7.0_40]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_40]
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76) [na:1.7.0_40]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:705) [na:1.7.0_40]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242) [na:1.7.0_40]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.
java:161) [na:1.7.0_40]        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150) [na:1.7.0_40]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146) [na:1.7.0_40]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138) [na:1.7.0_40]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91) [na:1.7.0_40]
```

May I contribute with an eml reader?

**Comment by arthurblake** [comment]
Did these changes ever get merged? Looked like the start of something useful...

**Comment by anlar** [comment]
Hello,

In case if anyone else needs client that can handle html emails, I've started [LunaticSMTP](https://github.com/anlar/LunaticSMTP) project.

It's not directly based on that project but it's like a reimplementation of FakeSMTP with JavaFX. It's using JFX's WebView (with it's built-in WebKit) to display emails. Also because of JFX usage minimum required Java version was bumped to 8u40.

**Comment by SpyroTEQ** [comment]
I know this is old, but I hope it would actually be *closed without being merged*, because one can also tell Windows (or Linux or whatever) to open *.eml files with the software they love (like, for me, Thunderbird) and I'm afraid merging such viewer into FakeSMTP will remove this nice behavior (one can still tell their OS to open *.eml file with the suggested viewer if one prefers)
