### ISSUE TITLE
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "main"

### ISSUE THREAD

**Issue by yrkhanal** [Nilhcem/FakeSMTP#74]
ndsl-scss-2270:target khanaly$ java -jar fakeSMTP-2.1-SNAPSHOT.jar -p 2525 -a localhost

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "main"

**Comment by yrkhanal** [comment]
Used to work before out of box but now complied source code still has issue

**Comment by yrkhanal** [comment]
I am using openJDK not sure if that is the cause ?
ndsl-scss-2270:target khanaly$ java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_192-b12)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.192-b12, mixed mode)

**Comment by yrkhanal** [comment]
T E S T S
-------------------------------------------------------
Running com.nilhcem.fakesmtp.integration.SendEmailsIT
04 Jan 2019 15:15:50 INFO  com.nilhcem.fakesmtp.integration.SendEmailsIT - Launching integration tests...
04 Jan 2019 15:15:50 INFO  com.nilhcem.fakesmtp.integration.SendEmailsIT - You need to run the project and launch the SMTP server on port 2525 before testing.
DEBUG: JavaMail version 1.4.4
DEBUG: successfully loaded resource: /META-INF/javamail.default.providers
DEBUG: Tables of loaded providers
DEBUG: Providers Listed By Class Name: {com.sun.mail.smtp.SMTPSSLTransport=javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Sun Microsystems, Inc], com.sun.mail.smtp.SMTPTransport=javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Sun Microsystems, Inc], com.sun.mail.imap.IMAPSSLStore=javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Sun Microsystems, Inc], com.sun.mail.pop3.POP3SSLStore=javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Sun Microsystems, Inc], com.sun.mail.imap.IMAPStore=javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Sun Microsystems, Inc], com.sun.mail.pop3.POP3Store=javax.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Sun Microsystems, Inc]}
DEBUG: Providers Listed By Protocol: {imaps=javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Sun Microsystems, Inc], imap=javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Sun Microsystems, Inc], smtps=javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Sun Microsystems, Inc], pop3=javax.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Sun Microsystems, Inc], pop3s=javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Sun Microsystems, Inc], smtp=javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Sun Microsystems, Inc]}
DEBUG: successfully loaded resource: /META-INF/javamail.default.address.map
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Sun Microsystems, Inc]
DEBUG SMTP: useEhlo true, useAuth false
DEBUG SMTP: trying to connect to host "localhost", port 2525, isSSL false
Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.559 sec <<< FAILURE! - in com.nilhcem.fakesmtp.integration.SendEmailsIT
sendEmailWithDots(com.nilhcem.fakesmtp.integration.SendEmailsIT)  Time elapsed: 0.165 sec  <<< ERROR!
org.apache.commons.mail.EmailException: Sending the email to the following server failed : localhost:2525
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:286)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:231)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1900)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:638)
	at javax.mail.Service.connect(Service.java:295)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400)
	at org.apache.commons.mail.Email.send(Email.java:1437)
	at com.nilhcem.fakesmtp.integration.SendEmailsIT.sendEmailWithDots(SendEmailsIT.java:116)

sendSimpleTestEmail(com.nilhcem.fakesmtp.integration.SendEmailsIT)  Time elapsed: 0.007 sec  <<< ERROR!
org.apache.commons.mail.EmailException: Sending the email to the following server failed : localhost:2525
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:286)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:231)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1900)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:638)
	at javax.mail.Service.connect(Service.java:295)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400)
	at org.apache.commons.mail.Email.send(Email.java:1437)
	at com.nilhcem.fakesmtp.integration.SendEmailsIT.sendSimpleTestEmail(SendEmailsIT.java:31)

sendHTMLFormattedEmail(com.nilhcem.fakesmtp.integration.SendEmailsIT)  Time elapsed: 0.013 sec  <<< ERROR!
org.apache.commons.mail.EmailException: Sending the email to the following server failed : localhost:2525
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:286)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:231)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1900)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:638)
	at javax.mail.Service.connect(Service.java:295)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400)
	at org.apache.commons.mail.Email.send(Email.java:1437)
	at com.nilhcem.fakesmtp.integration.SendEmailsIT.sendHTMLFormattedEmail(SendEmailsIT.java:76)

sendEmailWithAttachment(com.nilhcem.fakesmtp.integration.SendEmailsIT)  Time elapsed: 0.013 sec  <<< ERROR!
org.apache.commons.mail.EmailException: Sending the email to the following server failed : localhost:2525
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:286)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:231)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1900)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:638)
	at javax.mail.Service.connect(Service.java:295)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400)
	at org.apache.commons.mail.Email.send(Email.java:1437)
	at com.nilhcem.fakesmtp.integration.SendEmailsIT.sendEmailWithAttachment(SendEmailsIT.java:56)

sendEmailToManyRecipientsWithTwoHeaders(com.nilhcem.fakesmtp.integration.SendEmailsIT)  Time elapsed: 0.007 sec  <<< ERROR!
org.apache.commons.mail.EmailException: Sending the email to the following server failed : localhost:2525
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:286)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:231)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1900)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:638)
	at javax.mail.Service.connect(Service.java:295)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400)
	at org.apache.commons.mail.Email.send(Email.java:1437)
	at com.nilhcem.fakesmtp.integration.SendEmailsIT.sendEmailToManyRecipientsWithTwoHeaders(SendEmailsIT.java:103)

sendEmailWithBase64Subject(com.nilhcem.fakesmtp.integration.SendEmailsIT)  Time elapsed: 0.005 sec  <<< ERROR!
org.apache.commons.mail.EmailException: Sending the email to the following server failed : localhost:2525
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:286)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:231)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1900)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:638)
	at javax.mail.Service.connect(Service.java:295)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400)
	at org.apache.commons.mail.Email.send(Email.java:1437)
	at com.nilhcem.fakesmtp.integration.SendEmailsIT.sendEmailWithBase64Subject(SendEmailsIT.java:88)


Results :

Tests in error: 
  SendEmailsIT.sendEmailToManyRecipientsWithTwoHeaders:103 » Email Sending the e...
  SendEmailsIT.sendEmailWithAttachment:56 » Email Sending the email to the follo...
  SendEmailsIT.sendEmailWithBase64Subject:88 » Email Sending the email to the fo...
  SendEmailsIT.sendEmailWithDots:116 » Email Sending the email to the following ...
  SendEmailsIT.sendHTMLFormattedEmail:76 » Email Sending the email to the follow...
  SendEmailsIT.sendSimpleTestEmail:31 » Email Sending the email to the following...

Tests run: 6, Failures: 0, Errors: 6, Skipped: 0

**Comment by yrkhanal** [comment]
This is solved using latest openJDK lib
